# COMMON APPLICATION PROPERTIES
server:
  port: 0
  shutdown: graceful

spring:
  sql:
    init:
      mode: always
      platform: hsqldb
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  jmx:
    enabled: true

management.security.enabled: false
management.endpoints.web.exposure.include: "*"

spring.cloud.refresh.refreshable: false


# Logging
logging.level.org.springframework: INFO

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# Chaos Engineering
---
spring:
  config:
    activate:
      on-profile: chaos-monkey      
management.endpoint.chaosmonkey.enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://${MYSQL_SERVER_FULL_NAME}:3306/${MYSQL_DATABASE_NAME}?useSSL=false
    username: ${MYSQL_SERVER_ADMIN_LOGIN_NAME}
    password: ${MYSQL_SERVER_ADMIN_PASSWORD}
    initialization-mode: ALWAYS
  sql:
    init:
      mode: always
      platform: mysql
---
spring:
  config:
    activate:
      on-profile: passwordless
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    # url and username are injected by the service configuration as env vars
    azure:
      passwordless-enabled: true
  sql:
    init:
      mode: always
      platform: mysql
  cloud:
    azure:
      compatibility-verifier.enabled: false
      
---
spring:
  config:
    activate:
      on-profile: key-vault

MYSQL_SERVER_FULL_NAME: ${MYSQL-SERVER-FULL-NAME}
MYSQL_DATABASE_NAME: ${MYSQL-DATABASE-NAME}
MYSQL_SERVER_ADMIN_LOGIN_NAME: ${MYSQL-SERVER-ADMIN-LOGIN-NAME}
MYSQL_SERVER_ADMIN_PASSWORD: ${MYSQL-SERVER-ADMIN-PASSWORD}

azure:
  keyvault:
    enabled: true
    uri: ${AZURE_KEY_VAULT_URI}

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/